[package]
name = "scheduling"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "scheduling"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.1"
lazy_static = "1.0"
chrono = "0.4"
